task:
  freebsd_instance:
    matrix:
      image_family: freebsd-13-2
      image_family: freebsd-14-0-snap
  only_if: $CIRRUS_TAG !=~ '..*' # Prevent endless build loop from automatically created releases
  env:
    CIRRUS_CLONE_DEPTH: 1
    GITHUB_TOKEN: ENCRYPTED[98d43ce2ae88c126c10a7a113aa7ff7cafec515c006d73e6b852aec4e9db7d49be5c6e17f0f2b40858fcc6a599411b2d]

  Build_script:
    - ASSUME_ALWAYS_YES=yes pkg bootstrap -f 
    - pkg install -y plasma5-kwin git cmake pkgconf kf5-kwindowsystem kf5-extra-cmake-modules kf5-kcoreaddons kf5-kguiaddons kf5-kconfigwidgets plasma5-kdecoration qt5-core qt5-x11extras qt5-widgets qt5-qmake qt5-buildtools qt5-linguisttools patchelf wget zip
    - git clone https://github.com/helloSystem/BreezeEnhanced.git
    - cd BreezeEnhanced
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Release -DKDE_INSTALL_LIBDIR=lib -DBUILD_TESTING=OFF -DKDE_INSTALL_USE_QT_SYS_PATHS=ON ..
    - make install
    - cd ../..
    - sh ./makebundle.sh	
    - zip --symlinks -r KWin.app.zip KWin.app

  Upload_script:
    - export VER=$(uname -r | cut -d "-" -f 1)
    - case "$CIRRUS_BRANCH" in *pull/*) echo skipping since PR ;; * ) wget -c -q https://github.com/tcnksm/ghr/files/5247714/ghr.zip ; unzip ghr.zip ; ./ghr -delete -t "${GITHUB_TOKEN}" -u "${CIRRUS_REPO_OWNER}" -r "${CIRRUS_REPO_NAME}" -c "${CIRRUS_CHANGE_IN_REPO}" "${CIRRUS_BRANCH}"-"${VER}" KWin.app.zip ; esac
      
