task:
    freebsd_instance:
      matrix:
        - image: freebsd-13-release-amd64

    build_script:
      - ASSUME_ALWAYS_YES=yes pkg bootstrap -f 
      - pkg install -y plasma5_kwin
      - makebundle.sh	

