task:
    freebsd_instance:
      image_family: freebsd-13-0

    build_script:
      - ASSUME_ALWAYS_YES=yes pkg bootstrap -f 
      - pkg install -y plasma5-kwin git cmake pkgconf kf5-kwindowsystem kf5-extra-cmake-modules kf5-kcoreaddons kf5-kguiaddons kf5-kconfigwidgets plasma5-kdecoration qt5-core qt5-x11extras qt5-widgets qt5-qmake qt5-buildtools qt5-linguisttools
      - git clone https://github.com/helloSystem/BreezeEnhanced.git
      - cd BreezeEnhanced
      - mkdir build && cd build
      - cmake -DCMAKE_BUILD_TYPE=Release -DKDE_INSTALL_LIBDIR=lib -DBUILD_TESTING=OFF -DKDE_INSTALL_USE_QT_SYS_PATHS=ON ..
      - make install
      - cd ../..
      - sh ./makebundle.sh	

